
NUM_CLASSES = 1
IN_CHANNELS = 1

IMG_SIZE = (24, 128)
BATCH_SIZE = 96
PATCH_SIZE = 8
EMB_SIZE = 64
DEPTH = 24
NUM_HEADS = 4
FORWARD_EXPANSION = 4

SPLIT_TYPE = "time"
SPLIT_ARG = 120
VALIDATION_TYPE = "proportion"
VALIDATION_ARG = 0.0

CHANNEL_1 = None
NETWORK = 'vit'
REPLICATE_MODE = 'merge'

OPTIMIZER = "SGD"
PERTURBATION = 5e-3
PERTURBATION_LOSS_LIM = 0.75
DROPOUT = 0.05

DATA_FUNC = 'load_cd_data_24x128'
OUT_DIR = 'output/cd_24x128_more_complex'
