
NUM_CLASSES = 1
IN_CHANNELS = 1

IMG_SIZE = (12, 64)
BATCH_SIZE = 128
PATCH_SIZE = 4
EMB_SIZE = 48
DEPTH = 16
NUM_HEADS = 8
FORWARD_EXPANSION = 8

SPLIT_TYPE = "time"
SPLIT_ARG = 120.0

CHANNEL_1 = None
NETWORK = 'vit'
REPLICATE_MODE = 'merge'

OPTIMIZER = "SGD"
PERTURBATION = 5e-3
PERTURBATION_LOSS_LIM = 0.75
DROPOUT = 0.05

DATA_FUNC = 'load_cd_data_12x64'
OUT_DIR = 'output/12x_complex'
