
NUM_CLASSES = 1
IN_CHANNELS = 2

IMG_SIZE = (24, 128)
BATCH_SIZE = 96
PATCH_SIZE = 8
EMB_SIZE = 32
DEPTH = 6
NUM_HEADS = 4
FORWARD_EXPANSION = 2

SPLIT_TYPE = "time"
SPLIT_ARG = 120.0

CHANNEL_1 = None
NETWORK = 'vit'
REPLICATE_MODE = 'channels'

OPTIMIZER = "SGD"
PERTURBATION = 5e-3
PERTURBATION_LOSS_LIM = 0.75	
DROPOUT = 0.05

OUT_DIR = 'output/24x_120_repl'
INIT_MODEL_PATH = None
